# Generated by Django 4.0 on 2024-02-08 10:22

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='username', unique=True)),
                ('is_staff', models.BooleanField(default=False, verbose_name='статус персонала')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=455, verbose_name='ФИО')),
                ('phone_number', models.IntegerField(verbose_name='Номер телефона')),
                ('postal_code', models.IntegerField(verbose_name='Почтовый код')),
                ('country', models.CharField(blank=True, choices=[('RUSSIA', 'Россия'), ('BELARUS', 'Беларусь'), ('KAZAKHSTAN', 'Казахстан')], max_length=20, null=True, verbose_name='Страна')),
                ('delivery_address', models.CharField(max_length=455, verbose_name='Адрес доставки')),
                ('name_address', models.CharField(blank=True, max_length=455, verbose_name='Сохранить как')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адресная книга',
                'verbose_name_plural': 'Адресная книга пользователей',
            },
        ),
    ]
