# Generated by Django 4.0 on 2023-08-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='delivery_address',
            field=models.TextField(help_text='Введите полный адрес доставки (Страна, Город, Улица, Дом)', null=True, verbose_name='Полный адрес доставки'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='delivery_index',
            field=models.IntegerField(help_text='Это индекс почтового отделения, куда будет доставлена посылка из вашего заказа', null=True, verbose_name='Индекс'),
        ),
    ]
