# Generated by Django 4.0 on 2023-08-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Введите полный адрес доставки (Страна, Город, Улица, Дом)', null=True, verbose_name='Полный адрес доставки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='delivery_index',
            field=models.IntegerField(blank=True, help_text='Это индекс почтового отделения, куда будет доставлена посылка из вашего заказа', null=True, verbose_name='Индекс'),
        ),
    ]
