# Generated by Django 4.0 on 2024-02-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вопроса (Тема)')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('response', models.TextField(blank=True, verbose_name='Ответ')),
                ('answered', models.BooleanField(default=False, verbose_name='Ответить')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='ReviewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('avatar', models.ImageField(upload_to='images_avatars/', verbose_name='Аватар')),
                ('review', models.TextField(verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
