# Generated by Django 4.0 on 2023-06-28 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='mainpart',
            name='motorcycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.motorcycle', verbose_name='Мото/Двигатель'),
        ),
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.IntegerField(verbose_name='№'),
        ),
    ]
