# Generated by Django 4.0 on 2023-08-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpart',
            name='image',
            field=models.ImageField(blank=True, upload_to='mainpart/'),
        ),
    ]
