# Generated by Django 4.0 on 2023-08-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_delivery_address_and_more'),
        ('basket', '0003_remove_cartitem_cart_remove_cartitem_part_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_parts', to='basket.checkoutcart', verbose_name='Оформленный заказ')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.part', verbose_name='Запчасть')),
            ],
        ),
    ]
