# Generated by Django 4.0 on 2023-08-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_mainpart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='code',
            field=models.CharField(blank=True, max_length=150, verbose_name='Уникальный код'),
        ),
        migrations.AddField(
            model_name='part',
            name='item',
            field=models.CharField(blank=True, max_length=150, verbose_name='Артикул'),
        ),
    ]
